
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  servlet:
    context-path: /
  port: 8030
spring:
  application:
    name: reservations
  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 600
      payment-timeout: 1800
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2


security:
  jwt:
    token:
      secret-key: sQLOufSUuiIpxT3Rh772VaABdyj85UBUUG12f-V12ifa-wQlj2XssmOYI31-7Isv
      issuer: ace


